version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5e:b7:a8:8c:9b:16:ef:87:f4:6d:9a:11:5e:d8:da:10"
      - run:
          name: Prettier check
          command: |
            npm run prettier-check
      - run:
          name: Build Docs
          command: |
            npm install
            npm run doc
      - run:
          name: Deploy
          command: | 
            ssh-keyscan -H ines.cs.unibo.it >> ~/.ssh/known_hosts
            scp -r src/scripts/api/ antonio.lopez2@ines.cs.unibo.it:/home/web/site202118/html/scripts/
            scp src/index.js antonio.lopez2@ines.cs.unibo.it:/home/web/site202118/html/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
